name: mamudo_com
description: Mahmut Taskiran's personal web site.

publish_to: 'none'

version: 2.0.4+4

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/localizations/en.json
    - assets/localizations/tr.json
    - assets/images/profile_0.jpeg
    - assets/images/blueoperation.webp
    - assets/images/polyingo.png
    - assets/about_tr.txt
    - assets/about_en.txt